// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4M14x5b7TlkyfboeZ2f4aRBQ1xHGEYA',
    appId: '1:200111128957:web:6a85ffb6083dd0ca748c14',
    messagingSenderId: '200111128957',
    projectId: 'flutter-task-app-ae5aa',
    authDomain: 'flutter-task-app-ae5aa.firebaseapp.com',
    storageBucket: 'flutter-task-app-ae5aa.firebasestorage.app',
    measurementId: 'G-SMSCB5NTK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vB0hYgzjJUasz12J2txILx6fOrcDjXo',
    appId: '1:200111128957:android:54d79b908701968e748c14',
    messagingSenderId: '200111128957',
    projectId: 'flutter-task-app-ae5aa',
    storageBucket: 'flutter-task-app-ae5aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdWO9Kru0bqpCTB5tZ4CsJjTVGTHVX878',
    appId: '1:200111128957:ios:aa98fe2aa9052154748c14',
    messagingSenderId: '200111128957',
    projectId: 'flutter-task-app-ae5aa',
    storageBucket: 'flutter-task-app-ae5aa.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdWO9Kru0bqpCTB5tZ4CsJjTVGTHVX878',
    appId: '1:200111128957:ios:aa98fe2aa9052154748c14',
    messagingSenderId: '200111128957',
    projectId: 'flutter-task-app-ae5aa',
    storageBucket: 'flutter-task-app-ae5aa.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi4M14x5b7TlkyfboeZ2f4aRBQ1xHGEYA',
    appId: '1:200111128957:web:d5619d12fa63753e748c14',
    messagingSenderId: '200111128957',
    projectId: 'flutter-task-app-ae5aa',
    authDomain: 'flutter-task-app-ae5aa.firebaseapp.com',
    storageBucket: 'flutter-task-app-ae5aa.firebasestorage.app',
    measurementId: 'G-LQ1KK2TX5E',
  );
}
